### ISSUE TITLE
simple prospective simulation

### ISSUE THREAD

**Issue by r-leyshon** [oguerrer/ppi#9]
This may be my own misunderstanding, apologies if this is the case.

In `tutorials/03 - simple_prospective.ipynb`, there is the following cell:

```
sample_size = 100 # number of Monte Carlo simulations

outputs = []
for sample in range(sample_size):
    output = ppi.run_ppi(I0, alphas, alphas_prime, betas, A=A, R=R, qm=qm, rl=rl,
                Imax=Imax, Imin=Imin, Bs=Bs, B_dict=B_dict, T=T, G=goals)
    outputs.append(output)
```

* Should the first argument for `ppi.run_ppi()` in this instance be `IF`?
* The text refers to the development gap in 10 years, though `T=30`. Should `T=10`?

**Comment by oguerrer** [comment]
1. The cell that loads the data already loads I0 from the IF values of the indicators dataset.
2. The tutorial on expenditure data explains that T is not the same as calendar time. In ehse turorial, in particular, because the model is calibrated with T=69, it means that every 3 computational steps equal one calendar year. Thus, to simulate 10 years in the future, T needs to be 30.

**Comment by r-leyshon** [comment]
@oguerrer many thanks for confirming. You are correct, the explanation of T is apparent within the expenditure tutorial. As you may have guessed, I skipped this due to lacking this data. This was a mistake as the guidance on the use of T was very useful. 

I had missed the line on I0 = IF. I'll put this down to me reproducing your work with different data. Thanks for your help on this and sorry for all the issues.
